<img src="img/logoitqv1.jpg" width="500">
<br>

# PAO25_25_07_Python_Pandas

## 0.1 PAO 25-25 - Pandas
<br>

<img src="img/python_logo.png" width="300">
<br>

*Jesús Viera* https://github.com/Vierita23/machinelearning

# 1 Pandas

• Librería (de facto estándar) para estructurar datos tabulares
• Multivariable (string, int, float, bool…)
• Dos clases:
  – Series (1 dimensión)
  – DataFrames (2+ dimensiones)

In [1]:
# Instalar pandas en el intérprete Python que ejecuta este notebook
import sys
# subprocess permite lanzar comandos del sistema (como pip) desde Python
import subprocess

# Ejecutamos pip install usando el mismo Python del kernel (evita instalar en otro entorno)
subprocess.run(
    # Lista de argumentos: python -m pip install pandas numpy en modo silencioso (-q)
    [sys.executable, "-m", "pip", "install", "pandas", "numpy", "-q"],
    # check=False: no lanza excepción si pip devuelve código de error
    check=False,
)

# Mostramos qué ejecutable de Python está usando el notebook
print("Python:", sys.executable)

Python: C:\Users\Jesus\anaconda3\envs\Machine2026\python.exe

In [2]:
# Importamos Pandas con alias 'pd': librería estándar para tablas y series
import pandas as pd
# Importamos las clases Series (1D) y DataFrame (2D) directamente
from pandas import Series, DataFrame
# display renderiza DataFrames/Series con formato HTML en el notebook
from IPython.display import display

In [3]:
# Consultamos la versión instalada de Pandas (útil para compatibilidad de API)
pd.__version__

'3.0.3'

# 2 Series

• Datos unidimensionales (similar a NumPy)
• Elementos + índices modificables

In [4]:
# Creamos una Serie: vector 1D con índice automático (0, 1, 2...)
countries = pd.Series(['Spain','Andorra','Gibraltar','Portugal','France'])
# Mostramos la Serie completa con índice y valores
print(countries)

0        Spain
1      Andorra
2    Gibraltar
3     Portugal
4       France
dtype: str

In [5]:
# Creamos Serie con índice personalizado: las etiquetas no tienen que ser 0,1,2...
countries = pd.Series(['Spain','Andorra','Gibraltar','Portugal','France'],
                      # index=range(10,60,10) asigna etiquetas 10, 20, 30, 40, 50
                      index=range(10,60,10))
# Verificamos que cada país queda asociado a su etiqueta de índice
print(countries)

10        Spain
20      Andorra
30    Gibraltar
40     Portugal
50       France
dtype: str

In [6]:
# Los índices pueden ser strings u otros tipos, no solo enteros
football_cities = pd.Series(['Barcelona','Madrid','Valencia','Sevilla'],
                            # Índices semánticos 'a','b','c','d' para acceso por etiqueta
                            index=['a','b','c','d'])
# Mostramos la Serie con índice de letras
print(football_cities)

a    Barcelona
b       Madrid
c     Valencia
d      Sevilla
dtype: str

In [7]:
# Atributos de la Serie: nombre de la serie y nombre del índice
football_cities.name = 'Ciudades con dos equipos en primera' # nombrar la Serie
# index.name describe la columna de etiquetas (como cabecera del índice)
football_cities.index.name = 'Id' # Describir los índices
# Mostramos la Serie con metadatos de nombre aplicados
print(football_cities)

Id
a    Barcelona
b       Madrid
c     Valencia
d      Sevilla
Name: Ciudades con dos equipos en primera, dtype: str

In [8]:
# Acceso por posición entera: iloc[2] devuelve el 3er elemento (índice 0-based)
print(football_cities.iloc[2])
# Acceso por etiqueta semántica: ['c'] busca el valor cuyo índice es 'c'
print(football_cities['c'])
# Comprobamos que ambos accesos devuelven el mismo valor (Valencia)
print(football_cities['c'] == football_cities.iloc[2])

Valencia
Valencia
True

# 3 Tratamiento similar a ndarray

In [9]:
# Selección múltiple por etiquetas: devuelve sub-Serie con índices 'a' y 'c'
print(football_cities[ ['a','c'] ])
# Equivalente por posición: iloc[[0,3]] toma el 1er y 4to elemento
print(football_cities.iloc[[0, 3]])

Id
a    Barcelona
c     Valencia
Name: Ciudades con dos equipos en primera, dtype: str
Id
a    Barcelona
d      Sevilla
Name: Ciudades con dos equipos en primera, dtype: str

In [10]:
# Slicing semántico: desde el inicio hasta 'c' (incluye ambos extremos)
print(football_cities[:'c']) # incluye ambos extremos con el indice semantico
# Slicing posicional: iloc[:2] toma posiciones 0 y 1 (excluye el 2)
print(football_cities.iloc[:2])

Id
a    Barcelona
b       Madrid
c     Valencia
Name: Ciudades con dos equipos en primera, dtype: str
Id
a    Barcelona
b       Madrid
Name: Ciudades con dos equipos en primera, dtype: str

In [11]:
# Convertimos la sub-Serie a lista de Python (solo los valores)
lista = list(football_cities[:'c'])
# Mostramos la lista resultante ['Barcelona', 'Madrid', 'Valencia']
print(lista)
# Confirmamos que el tipo es list, no Series
print(type(lista))

['Barcelona', 'Madrid', 'Valencia']
<class 'list'>

In [12]:
# Consultamos el tipo de dato del objeto
type(football_cities[:'c'])

pandas.Series

In [13]:
# Convertimos la sub-Serie a ndarray de NumPy para operaciones vectoriales
import numpy as np
# np.array extrae los valores y los convierte en array NumPy
cities = np.array(football_cities[:'c'])
# Mostramos el array NumPy resultante
print(cities)
# Verificamos el tipo: ndarray permite operaciones matemáticas eficientes
print(type(cities))

['Barcelona' 'Madrid' 'Valencia']
<class 'numpy.ndarray'>

In [14]:
# Convertimos la sub-Serie a diccionario {índice: valor}
lista = dict(football_cities[:'c'])
# Muestra pares clave-valor, ej: {'a': 'Barcelona', 'b': 'Madrid', ...}
print(lista)

{'a': 'Barcelona', 'b': 'Madrid', 'c': 'Valencia'}

In [15]:
# Máscaras booleanas: filtrar elementos que cumplan una condición
fibonacci = pd.Series([0, 1, 1, 2, 3, 5, 8, 13, 21])
# Mostramos la Serie completa de Fibonacci
print(fibonacci)
# Creamos máscara: True donde el valor es mayor que 10
mask = fibonacci > 10
# La máscara es una Serie de booleanos alineada con el índice original
print(mask)
# Aplicamos la máscara: solo devuelve valores donde mask es True (13 y 21)
print(fibonacci[mask])
# Serie de comparación con los dos valores filtrados
dst = pd.Series([13,21])
# Mostramos la Serie de referencia para comparar
print(dst)
# equals() compara valores e índice: False porque dst tiene índice 0,1 y fibonacci 7,8
dst.equals(fibonacci)
# Extraemos los valores >10 y los guardamos en fb
fb = fibonacci[mask]
# reset_index(drop=True) renumera el índice a 0,1,... sin conservar el original
fb.reset_index(drop=True, inplace=True)
# Ahora fb tiene índice [0,1] con valores [13, 21]
print(fb)
# Tras reindexar, fb y dst tienen mismos valores e índice → True
dst.equals(fb)

0     0
1     1
2     1
3     2
4     3
5     5
6     8
7    13
8    21
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7     True
8     True
dtype: bool
7    13
8    21
dtype: int64
0    13
1    21
dtype: int64
0    13
1    21
dtype: int64

True

In [16]:
# Las Series de Pandas son compatibles con funciones universales de NumPy
import numpy as np
# np.sum suma todos los elementos de la Serie (ignora NaN por defecto)
print(np.sum(fibonacci))

54

In [17]:
# np.where reemplaza valores según condición: útil para imputar NaN
distances = pd.Series([12.1,np.nan,12.8,76.9,6.1,7.2])
# Si no es NaN → conserva el valor; si es NaN → sustituye por 2
valid_distances = np.where(pd.notnull(distances),distances,2)
# Resultado: array NumPy con NaN reemplazados por 2
print(valid_distances)
# np.where devuelve ndarray, no Series
print(type(valid_distances))

[12.1  2.  12.8 76.9  6.1  7.2]
<class 'numpy.ndarray'>

## 3.0.1 Iteración

In [18]:
# Iteración 1: recorrer solo los valores de la Serie
for value in fibonacci:
    # Cada iteración imprime un término de la sucesión
    print('Value: ' + str(value))
# # iterar sobre indices
# Iteración 2: recorrer solo las etiquetas del índice
for index in fibonacci.index:
    # Cada iteración imprime una etiqueta de índice (0, 1, 2...)
    print('Index: ' + str(index))

Value: 0
Value: 1
Value: 1
Value: 2
Value: 3
Value: 5
Value: 8
Value: 13
Value: 21
Index: 0
Index: 1
Index: 2
Index: 3
Index: 4
Index: 5
Index: 6
Index: 7
Index: 8

In [19]:
# items() devuelve pares (índice, valor) en cada iteración
for index, value in fibonacci.items():
    # Mostramos índice y valor juntos en cada línea
    print('Index: ' + str(index) + ' Value: ' + str(value))

Index: 0 Value: 0
Index: 1 Value: 1
Index: 2 Value: 1
Index: 3 Value: 2
Index: 4 Value: 3
Index: 5 Value: 5
Index: 6 Value: 8
Index: 7 Value: 13
Index: 8 Value: 21

In [20]:
# zip() combina manualmente índice y valores (alternativa a items())
for index, value in zip(fibonacci.index, fibonacci):
    # Mismo resultado que items(): empareja etiqueta con su valor
    print('Index: ' + str(index) + ' Value: ' + str(value))

Index: 0 Value: 0
Index: 1 Value: 1
Index: 2 Value: 1
Index: 3 Value: 2
Index: 4 Value: 3
Index: 5 Value: 5
Index: 6 Value: 8
Index: 7 Value: 13
Index: 8 Value: 21

## 3.1 Series como diccionarios

• Interpretar el índice como clave
• Acepta operaciones para diccionarios

In [21]:
# Desde dict: las claves del diccionario se convierten en índice de la Serie
serie = pd.Series( { 'Carlos' : 100, 'Marcos': 98} )
# index contiene las claves: ['Carlos', 'Marcos']
print(serie.index)
# values contiene los valores numéricos: [100, 98]
print(serie.values)
# Mostramos la Serie completa con índice y valores
print(serie)
# Confirmamos que el objeto es una Series de Pandas
print(type(serie))

Index(['Carlos', 'Marcos'], dtype='str')
[100  98]
Carlos    100
Marcos     98
dtype: int64
<class 'pandas.Series'>

In [22]:
# Las Series son mutables: podemos añadir, modificar y borrar por índice
serie['Pedro'] = 12
# Sobrescribimos el valor de 'Pedro' de 12 a 15 (misma clave, nuevo valor)
serie['Pedro']=15
# del elimina la entrada con índice 'Marcos' de la Serie
del serie['Marcos']
# Mostramos la Serie resultante: Carlos, Pedro (sin Marcos)
print(serie)

Carlos    100
Pedro      15
dtype: int64

In [23]:
# Consulta condicional: verificar si una etiqueta existe antes de acceder
# print(serie['Marcos'])
if 'Marcos' in serie:
    # Solo se ejecuta si 'Marcos' sigue en el índice (aquí ya fue eliminado)
    print(serie['Marcos'])
# Mostramos el estado actual de la Serie tras las operaciones anteriores
print(serie)

Carlos    100
Pedro      15
dtype: int64

## 3.2 Operaciones entre series

In [24]:
# Suma de Series: se alinean por índice, no por posición
# suma de valores con el mismo índice (NaN si no aparece en ambas)
serie1 = pd.Series([10,20,30,40], index=range(4) )
# serie2 solo tiene índices 0,1,2 → el índice 3 de serie1 quedará NaN
serie2 = pd.Series([1,2,3], index=range(3) )
# Suma elemento a elemento donde coinciden índices; NaN donde falta pareja
suma = serie1 + serie2
# Resultado: [11, 22, 33, NaN]
print(suma)

0    11.0
1    22.0
2    33.0
3     NaN
dtype: float64

In [25]:
# resta de series (similar a la suma)
print(serie1 - serie2)

0     9.0
1    18.0
2    27.0
3     NaN
dtype: float64

In [26]:
# Pre-filtrado: operar primero y luego reemplazar NaN resultantes
result = serie1 + serie2
# Detectamos valores nulos (NaN)
# isnull() crea máscara True donde hay NaN; asignamos 0 en esas posiciones
result[pd.isnull(result)] = 0 # mask con isnull()
# Ahora el índice 3 tiene 0 en lugar de NaN
print(result)

0    11.0
1    22.0
2    33.0
3     0.0
dtype: float64

### 3.2.1 Diferencias entre Pandas Series y diccionario

• Diccionario, es una estructura que relaciona las claves y los valores de forma arbitraria.
• Series, estructura de forma estricta listas de valores con listas de índice asignado en la posición.
• Series, es más eficiente para ciertas operaciones que los dicionarios.
• En las Series los valores de entrada pueden ser listas o Numpy arrays.
• En Series los índices semánticos pueden ser integers o caracteres, en los valores igual.
• Series se podría entender entre una lista y un diccionario Python, pero es de una dimensión.

# 4 DataFrame

• Datos tabulares (filas x columnas)
• Columnas: Series con índices compartidos

In [27]:
# DataFrame desde dict: cada clave es una columna, cada lista una columna de datos
diccionario = { "Nombre" : ["Marisa","Laura","Manuel"],
                # Segunda clave del dict: columna 'Edad' con 3 valores enteros
                "Edad" : [34,29,12] }
# Mostramos la estructura del diccionario antes de convertirlo
print(diccionario)
# las claves identifican columnas
# pd.DataFrame convierte el dict en tabla 3 filas × 2 columnas
frame = pd.DataFrame(diccionario)
# Renderizamos la tabla en el notebook
display(frame)

{'Nombre': ['Marisa', 'Laura', 'Manuel'], 'Edad': [34, 29, 12]}

   Nombre  Edad
0  Marisa    34
1   Laura    29
2  Manuel    12

In [28]:
# Mismo dict pero con índice de filas personalizado ['a','b','c']
diccionario = { "Nombre" : ["Marisa","Laura","Manuel"],
                # Columna 'Edad' paralela a 'Nombre' (misma longitud obligatoria)
                "Edad" : [34,29,12] }
# las claves identifican columnas
# index=['a','b','c'] etiqueta cada fila con letras en lugar de 0,1,2
frame = pd.DataFrame(diccionario, index = ['a', 'b', 'c'])
# Tabla con índice semántico visible en la primera columna
display(frame)

   Nombre  Edad
a  Marisa    34
b   Laura    29
c  Manuel    12

In [29]:
# columns define qué columnas crear y en qué orden (faltantes → NaN)
# además de 'index', el parámetro 'columns' especifica el número y orden de las columnas
frame = pd.DataFrame(diccionario, columns = ['Nacionalidad', 'Nombre', 'Edad', 'Profesion','Genero'])
# Columnas sin datos en el dict (Nacionalidad, Profesion, Genero) aparecen como NaN
display(frame)

  Nacionalidad  Nombre  Edad Profesion Genero
0          NaN  Marisa    34       NaN    NaN
1          NaN   Laura    29       NaN    NaN
2          NaN  Manuel    12       NaN    NaN

In [30]:
# Acceso a columna con corchetes: devuelve una Series (no un DataFrame)
nombres = frame['Nombre']
# Muestra la Serie con los nombres de cada fila
display(nombres)
# El tipo es Series: vector 1D con índice del DataFrame original
print(type(nombres))
# Accedemos a otra columna del mismo DataFrame
edades = frame['Edad']
# Serie con las edades de cada persona
display(edades)
# También es Series, una columna extraída del DataFrame
print(type(edades))

0    Marisa
1     Laura
2    Manuel
Name: Nombre, dtype: str

<class 'pandas.Series'>

0    34
1    29
2    12
Name: Edad, dtype: int64

<class 'pandas.Series'>

In [31]:
# Acceso con notación punto: solo funciona si el nombre no tiene espacios ni conflictos
#siempre que el nombre de la columna lo permita (espacios, ...)
nombres = frame.Profesion
# Muestra la columna Profesion (todos NaN en este ejemplo)
display(nombres)
# Consultamos el tipo de dato del objeto
type(nombres)

0    NaN
1    NaN
2    NaN
Name: Profesion, dtype: object

pandas.Series

In [32]:
# Acceso encadenado: columna + posición → valor escalar de la 1ª fila
# acceso al primer nombre del DataFrame frame??
print(frame['Nombre'][0])
# Equivalente con notación punto para la misma celda
print(frame.Nombre[0])
# También desde la variable nombres (Series) accedemos al índice 0
print(nombres[0])

Marisa
Marisa
nan

### 4.0.1 Formas de crear un DataFrame

• Con una Serie de pandas
• Lista de diccionarios
• Dicionario de Series de Pandas
• Con un array de Numpy de dos dimensiones
• Con array estructurado de Numpy

## 4.1 Modificar DataFrames

In [33]:
# Añadir columna nueva: asignar un valor escalar rellena todas las filas
diccionario = { "Nombre" : ["Marisa","Laura","Manuel"],
                # Columna Edad con las edades de las tres personas
                "Edad" : [34,29,12] }
# Creamos DataFrame con columnas extra vacías (NaN) para Nacionalidad, Profesion, Direccion
frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre', 'Edad','Profesion', 'Direccion'])
# Asignamos 'Desconocida' a toda la columna Direccion (broadcasting de escalar)
frame['Direccion'] = 'Desconocida'
# Tabla con la nueva columna rellena uniformemente
display(frame)

  Nacionalidad  Nombre  Edad Profesion    Direccion
0          NaN  Marisa    34       NaN  Desconocida
1          NaN   Laura    29       NaN  Desconocida
2          NaN  Manuel    12       NaN  Desconocida

In [34]:
# Lista con una dirección distinta para cada fila del DataFrame
lista_direcciones = ['Rue 13 del Percebe, 13', 'Evergreen Terrace, 3', 'Av de los Rombos, 12']

In [35]:
# Asignamos la lista: cada elemento se alinea con una fila por posición
frame['Direccion'] = lista_direcciones
# Cada fila recibe su dirección correspondiente de la lista
display(frame)

  Nacionalidad  Nombre  Edad Profesion               Direccion
0          NaN  Marisa    34       NaN  Rue 13 del Percebe, 13
1          NaN   Laura    29       NaN    Evergreen Terrace, 3
2          NaN  Manuel    12       NaN    Av de los Rombos, 12

In [36]:
# Añadir fila con loc: requiere valores para todas las columnas existentes
# añadir fila (requiere todos los valores)
user_2 = ['Alemania','Klaus',20, 'none','Desconocida']
# loc[3] crea/asigna la fila con índice 3 usando la lista en orden de columnas
frame.loc[3] = user_2
# DataFrame con la nueva fila de Klaus en la posición 3
display(frame)

  Nacionalidad  Nombre  Edad Profesion               Direccion
0          NaN  Marisa    34       NaN  Rue 13 del Percebe, 13
1          NaN   Laura    29       NaN    Evergreen Terrace, 3
2          NaN  Manuel    12       NaN    Av de los Rombos, 12
3     Alemania   Klaus    20      none             Desconocida

In [37]:
# Eliminar filas y columnas: drop no modifica in-place por defecto
# eliminar fila (similar a Series)
frame = pd.DataFrame(diccionario,columns=['Nacionalidad', 'Nombre', 'Edad', 'Profesion'])
# drop(2) elimina la fila con índice 2; hay que reasignar porque devuelve copia
frame = frame.drop(2) # por qué necesitamos reasignar el frame?
# Tabla sin la fila de Manuel (índice 2)
display(frame)
# drop con axis=1 elimina columnas; inplace=True modifica el DataFrame original
frame.drop('Nombre', axis = 1, inplace = True)
# DataFrame sin la columna Nombre
display(frame)

  Nacionalidad  Nombre  Edad Profesion
0          NaN  Marisa    34       NaN
1          NaN   Laura    29       NaN

  Nacionalidad  Edad Profesion
0          NaN    34       NaN
1          NaN    29       NaN

In [38]:
# del también elimina columnas, como alternativa a drop(axis=1)
#eliminar columna
del frame['Profesion']
# DataFrame final sin la columna Profesion
display(frame)

  Nacionalidad  Edad
0          NaN    34
1          NaN    29

In [39]:
# acceder a la traspuesta (como una matriz)
display(frame.T)

                0    1
Nacionalidad  NaN  NaN
Edad           34   29

## 4.2 Iteración

In [40]:
# Iterar un DataFrame devuelve los nombres de las columnas, no las filas
# iteración sobre el DataFrame?
frame = pd.DataFrame(diccionario, columns=['Nacionalidad', 'Nombre', 'Edad', 'Profesion'])
# Mostramos el DataFrame antes de iterar
display(frame)
# for a in frame recorre nombres de columnas: 'Nacionalidad', 'Nombre', etc.
for a in frame:
    # 'a' es el nombre de cada columna (string)
    print(a) # qué es 'a'?
    # El tipo de 'a' es str (nombre de columna)
    print(type(a))

  Nacionalidad  Nombre  Edad Profesion
0          NaN  Marisa    34       NaN
1          NaN   Laura    29       NaN
2          NaN  Manuel    12       NaN

Nacionalidad
<class 'str'>
Nombre
<class 'str'>
Edad
<class 'str'>
Profesion
<class 'str'>

In [41]:
# frame.values devuelve ndarray 2D con todos los datos (sin índices ni nombres)
# iteracion sobre filas
for value in frame.values:
    # Cada 'value' es un array NumPy con los valores de una fila
    print(value)
    # Tipo numpy.ndarray: fila como array de la fila i-ésima
    print(type(value))

[nan 'Marisa' 34 nan]
<class 'numpy.ndarray'>
[nan 'Laura' 29 nan]
<class 'numpy.ndarray'>
[nan 'Manuel' 12 nan]
<class 'numpy.ndarray'>

In [42]:
# Doble bucle: primero filas (values), luego cada celda de la fila
# iterar sobre filas y luego sobre cada valor?
for values in frame.values:
    # Bucle interno: recorre cada valor individual de la fila actual
    for value in values:
        # Imprime cada celda una a una (incluyendo NaN)
        print(value)

nan
Marisa
34
nan
nan
Laura
29
nan
nan
Manuel
12
nan

## 4.3 Indexación y slicing con DataFrames

In [43]:
# Lista de dicts con claves distintas: Pandas rellena NaN donde falta clave
d1 = {'ciudad':'Valencia', 'temperatura':10, 'o2':1}
# d2 no tiene 'o2' → esa celda será NaN en el DataFrame
d2 = {'ciudad':'Barcelona', 'temperatura':8}
# d3 solo tiene ciudad y temperatura
d3 = {'ciudad':'Valencia', 'temperatura':9}
# d4 añade humedad pero no o2 ni co2
d4 = {'ciudad':'Madrid', 'temperatura':10, 'humedad':80}
# d5 tiene humedad y co2
d5 = {'ciudad':'Sevilla', 'temperatura':15, 'humedad':50, 'co2':6}
# d6 tiene todas las claves posibles del conjunto
d6 = {'ciudad':'Valencia', 'temperatura':10, 'humedad':90, 'co2':10}
# Agrupamos los 6 registros en una lista para crear el DataFrame
ls_data = [d1, d2, d3, d4, d5, d6] # lista de diccionarios
# index='abcdef' etiqueta cada fila; columnas = unión de todas las claves
df_data = pd.DataFrame(ls_data, index = list('abcdef'))
# Tabla heterogénea: NaN donde cada dict no tenía esa clave
display(df_data)

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

In [44]:
# iloc: acceso por posición entera [fila, columna]
# Acceso a un valor concreto por indice posicional [row, col]
print(df_data.iloc[1,1])
# iloc[:3,:4] → primeras 3 filas y 4 primeras columnas
display(df_data.iloc[:3,:4])
# loc con escalares: fila 'a', columna 'temperatura' → valor único
display(df_data.loc['a', 'temperatura'])
# loc con rangos semánticos: filas hasta 'c', columnas hasta 'o2' (inclusivos)
display(df_data.loc[:'c', :'o2'])
# loc con slice de columnas: de 'temperatura' a 'o2' en filas hasta 'c'
display(df_data.loc[:'c', 'temperatura':'o2'])
# loc con lista de columnas: todas las filas, solo 'ciudad' y 'o2'
display(df_data.loc[:, ['ciudad','o2']])

8

      ciudad  temperatura   o2  humedad
a   Valencia           10  1.0      NaN
b  Barcelona            8  NaN      NaN
c   Valencia            9  NaN      NaN

np.int64(10)

      ciudad  temperatura   o2
a   Valencia           10  1.0
b  Barcelona            8  NaN
c   Valencia            9  NaN

   temperatura   o2
a           10  1.0
b            8  NaN
c            9  NaN

      ciudad   o2
a   Valencia  1.0
b  Barcelona  NaN
c   Valencia  NaN
d     Madrid  NaN
e    Sevilla  NaN
f   Valencia  NaN

In [45]:
# Acceso por nombre de columna: df['col'] devuelve una Series
# indexación con nombre de columna (por columnas)
print(df_data['ciudad']) # --> Series
# Doble corchete [['ciudad','o2']] devuelve DataFrame con esas columnas
display(df_data[['ciudad', 'o2']])

a     Valencia
b    Barcelona
c     Valencia
d       Madrid
e      Sevilla
f     Valencia
Name: ciudad, dtype: str

      ciudad   o2
a   Valencia  1.0
b  Barcelona  NaN
c   Valencia  NaN
d     Madrid  NaN
e    Sevilla  NaN
f   Valencia  NaN

In [46]:
# df[0] busca una COLUMNA llamada 0, no la fila 0 → KeyError
# indexación con índice posicional (no permitido!). Esto busca columna.
try:
    # Intentamos acceder con entero como si fuera posición de fila
    df_data[0]
# Capturamos KeyError: no existe columna con nombre 0
except KeyError as e:
    # Mostramos el tipo de error y el mensaje para entender el fallo
    print(type(e).__name__ + ':', e)

KeyError: 0

In [47]:
# indexar por posición con 'iloc'
print(df_data.iloc[0]) # --> Series de la primera fila (qué marca los índices)

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

In [48]:
# indexar semántico con 'loc'
df_data.loc['a'] # --> Series de la fila con índice 'a'

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

In [49]:
# indexar semántico con 'loc'
df_data.loc[:'b'] # --> DataFrame de la fila con índice 'a' y 'b'

      ciudad  temperatura   o2  humedad  co2
a   Valencia           10  1.0      NaN  NaN
b  Barcelona            8  NaN      NaN  NaN

In [50]:
# Selección por etiqueta de índice (semántica)
df_data.loc[:'b'].loc[:,["o2", "humedad"]] # slicing anidado

    o2  humedad
a  1.0      NaN
b  NaN      NaN

In [51]:
# SettingWithCopyWarning: modificar una vista afecta al DataFrame original
# si se modifica una porcion del dataframe se modifica el dataframe original (referencia)
display(df_data)
# loc['a'] devuelve una vista (o copia) de la fila 'a' como Series
serie = df_data.loc['a']
# Mostramos la fila extraída
print(serie)
# Modificar serie.iloc[2] cambia también df_data (problema de referencia)
serie.iloc[2] = 3000 # setting with copy warning!!!
# El valor 3000 aparece en df_data original
display(df_data)
# .copy() crea una copia independiente para modificar sin afectar el original
df_2 = df_data.loc['a'].copy()
# Ahora la modificación solo afecta a df_2
df_2.iloc[2] = 3000
# df_2 modificado con o2=3000
display(df_2)
# df_data conserva su valor original en esa celda
display(df_data)

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

ciudad         Valencia
temperatura          10
o2                  1.0
humedad             NaN
co2                 NaN
Name: a, dtype: object

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

ciudad         Valencia
temperatura          10
o2                 3000
humedad             NaN
co2                 NaN
Name: a, dtype: object

      ciudad  temperatura   o2  humedad   co2
a   Valencia           10  1.0      NaN   NaN
b  Barcelona            8  NaN      NaN   NaN
c   Valencia            9  NaN      NaN   NaN
d     Madrid           10  NaN     80.0   NaN
e    Sevilla           15  NaN     50.0   6.0
f   Valencia           10  NaN     90.0  10.0

In [52]:
# ambos aceptan 'axis' como argumento
# df_data.iloc(axis=1)[0] # --> todos los valores asignados a la primera columna 'ciudad'
df_data.loc(axis=1)['ciudad'] # --> equivalente frame['ciudad']

a     Valencia
b    Barcelona
c     Valencia
d       Madrid
e      Sevilla
f     Valencia
Name: ciudad, dtype: str

In [53]:
# Índice no ordenado: fila con index=0 no es necesariamente la primera fila
# qué problema puede tener este fragmento?
frame = pd.DataFrame({"Name" : ['Carlos','Pedro'], "Age" : [34,22]}, index=[1,0])
# Carlos tiene index=1 (primera fila visual), Pedro tiene index=0
display(frame)

     Name  Age
1  Carlos   34
0   Pedro   22

In [54]:
# iloc[0] = primera fila por posición; loc[0] = fila con etiqueta 0
# por defecto, pandas interpreta índice posicional --> error en frames
# cuando hay posible ambigüedad, utilizar loc y iloc
print('Primera fila
')
# iloc[0] devuelve Pedro (posición 0 en el DataFrame visual)
print(frame.iloc[0])
# Imprimimos separador para distinguir ambos resultados
print('
Elemento con index 0
')
# loc[0] devuelve la fila cuya etiqueta de índice es 0 (Pedro también aquí)
print(frame.loc[0])

Primera fila

Name    Carlos
Age         34
Name: 1, dtype: object

Elemento con index 0

Name    Pedro
Age        22
Name: 0, dtype: object

## 4.4 Objeto Index de Pandas

In [55]:
# pd.Index: objeto inmutable que representa el índice de filas/columnas
# Contrucción de índices
ind = pd.Index([2, 3, 5, 23, 26])
# ind[3] accede al 4to elemento del índice → valor 23
print(ind[3])
# Slicing del índice: cada 2 posiciones → [2, 5, 26]
print(ind[::2])

23
Index([2, 5, 26], dtype='int64')

In [56]:
# Podemos pasar un pd.Index al crear el DataFrame como etiquetas de fila
# usar un objeto index al crear dataframe
frame = pd.DataFrame({"Name" : ['Carlos','Pedro', 'Manolo', 'Luis', 'Alberto'], "Age" : [34,22,15,55,23]}, index=ind)
# Filas etiquetadas con 2, 3, 5, 23, 26 en lugar de 0-4
display(frame)

       Name  Age
2    Carlos   34
3     Pedro   22
5    Manolo   15
23     Luis   55
26  Alberto   23

In [57]:
# Los objetos Index son inmutables: no se puede cambiar un elemento
# Son inmutables! No se modifican los datos.
try:
    # Intentar asignar ind[3]=8 lanza TypeError
    ind[3] = 8
# Capturamos TypeError: los índices no admiten asignación
except TypeError as e:
    # Mostramos el error para confirmar la inmutabilidad
    print(type(e).__name__ + ':', e)

TypeError: Index does not support mutable operations

In [58]:
# set_index convierte una columna en el nuevo índice del DataFrame
# change index column
frame = pd.DataFrame({"Name" : ['Carlos','Pedro', 'Manolo', 'Luis', 'Alberto'], "Age" : [34,22,15,55,23]}, index=ind)
# DataFrame con índice numérico personalizado antes del cambio
display(frame)
# Age pasa a ser el índice; la columna Age desaparece como columna
frame.set_index('Age', inplace=True)
# Ahora las filas se identifican por edad; Name es la única columna
display(frame)

       Name  Age
2    Carlos   34
3     Pedro   22
5    Manolo   15
23     Luis   55
26  Alberto   23

        Name
Age
34    Carlos
22     Pedro
15    Manolo
55      Luis
23   Alberto

## 4.5 Slicing

In [59]:
# Slicing de filas: sintaxis similar a listas y Series
# slice por filas
d_and_d_characters = {'Name' : ['bundenth','theorin','barlok'], 'Strength' : [10,12,19], 'Wisdom' : [20,13,6]}
# DataFrame de personajes D&D con índice 'a','b','c'
character_data = pd.DataFrame(d_and_d_characters, index=['a','b','c'])
# Tabla completa de 3 personajes
display(character_data)
# [:-1] excluye la última fila ('c')
display(character_data[:-1])
# [1:2] solo la fila en posición 1 ('b'), equivalente a iloc[1:2]
display(character_data[1:2])

       Name  Strength  Wisdom
a  bundenth        10      20
b   theorin        12      13
c    barlok        19       6

       Name  Strength  Wisdom
a  bundenth        10      20
b   theorin        12      13

      Name  Strength  Wisdom
b  theorin        12      13

In [60]:
# slicing para columnas
display(character_data[['Name','Wisdom']])

       Name  Wisdom
a  bundenth      20
b   theorin      13
c    barlok       6

In [61]:
# iloc y loc para slicing avanzado con filas y columnas
#slicing con 'loc' e 'iloc'
# iloc[1:] → desde la fila posición 1 hasta el final
display(character_data.iloc[1:])
# loc[:'b','Name':'Strength'] → filas hasta 'b', columnas de Name a Strength (inclusivo)
display(character_data.loc[:'b','Name':'Strength'])

      Name  Strength  Wisdom
b  theorin        12      13
c   barlok        19       6

       Name  Strength
a  bundenth        10
b   theorin        12

¿Cómo filtrar filas y columnas? Por ejemplo, para todos los personajes, obtener 'Name' y 'Strength'

In [62]:
# usando 'loc' para hacer slicing
display(character_data.loc[:,'Name':'Strength'])

       Name  Strength
a  bundenth        10
b   theorin        12
c    barlok        19

In [63]:
# usando 'loc' para buscar específicamente filas y columnas
display(character_data.loc[ ['a','c'], ['Name','Wisdom'] ])

       Name  Wisdom
a  bundenth      20
c    barlok       6

In [64]:
# Selección avanzada con listas de posiciones en iloc
# lo mismo con 'iloc'?
# iloc[[0,2],[0,2]] → filas 0 y 2, columnas 0 y 2 (Name y Wisdom)
display(character_data.iloc[[0,2],[0,2]])
# iloc[[0,-1],[0,-1]] → primera y última fila, primera y última columna
display(character_data.iloc[[0,-1],[0,-1]])

       Name  Wisdom
a  bundenth      20
c    barlok       6

       Name  Wisdom
a  bundenth      20
c    barlok       6

In [65]:
# lista de los personajes con el atributo Strength > 11
display(character_data.loc[character_data['Strength'] > 11, ['Name', 'Strength']])

      Name  Strength
b  theorin        12
c   barlok        19

In [66]:
# listar los personajes con Strength > 15 o Wisdom > 15
display(character_data.loc[(character_data['Strength'] > 15) | (character_data['Wisdom'] > 15)])

       Name  Strength  Wisdom
a  bundenth        10      20
c    barlok        19       6

# 5 Cargar y guardar datos en pandas

In [67]:
# Exportar DataFrame a CSV con to_csv (comentado para no sobrescribir)
# Guardar a csv
import os
# Construimos ruta relativa al directorio res/
ruta = os.path.join("res" ,"o_d_d_characters.csv")
#character_data.to_csv(ruta, sep=';') # sep por defecto: ','

In [68]:
# read_csv carga el archivo separado por ';' en un nuevo DataFrame
# Leemos datos desde archivo
loaded = pd.read_csv(ruta, sep=';')
# Mostramos el DataFrame cargado desde disco
display(loaded)

  Unnamed: 0      Name  Strength  Wisdom
0          a  bundenth        10      20
1          b   theorin        12      13
2          c    barlok        19       6

In [69]:
# Ruta al dataset Titanic en la carpeta res/
ruta = os.path.join("res","titanic.csv")

In [70]:
# Carga estándar: primera fila como cabecera, índice automático 0,1,2...
# Leemos datos desde archivo
titanic = pd.read_csv(ruta, sep=',')
# Tabla Titanic con columnas inferidas del CSV
display(titanic)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [71]:
# index_col=0 usa la primera columna del CSV como índice de filas
# Leemos datos desde archivo
loaded = pd.read_csv(ruta, sep=',', index_col = 0)
# La columna 0 del CSV ya no aparece como columna, sino como índice
display(loaded)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

otros argumentos to_csv()

• na_rep='string' –> representar valores NaN en el archivo csv

otros argumentos read_csv()

• na_values='string'

Pandas también ofrece funciones para leer/guardar a otros formatos estándares: JSON, HDF5 o Excel en su API

# 6 Ejemplo práctico en pandas

• MovieLens dataset
• Reviews de películas
• 1 millón de entradas
• Datos demográficos de usuarios

In [72]:
# Importaciones para descargar y descomprimir el dataset MovieLens
# Importamos NumPy: arrays y operaciones numéricas
import numpy as np
# Importamos Pandas: DataFrames y Series
import pandas as pd
# Importamos módulo zipfile
import zipfile # para descomprimir archivos zip
# Importamos módulo urllib.request
import urllib.request # para descargar de URL
# Importamos sistema operativo y rutas
import os
# URL del dataset MovieLens 1M (1 millón de valoraciones)
url = 'http://files.grouplens.org/datasets/movielens/ml-1m.zip'
# Ruta local donde se guardará el archivo zip descargado
ruta = os.path.join("res", "ml-1m.zip")
# Descarga el zip desde la URL y lo guarda en ruta
urllib.request.urlretrieve(url, ruta)

('res\\ml-1m.zip', <http.client.HTTPMessage at 0x29779deaad0>)

In [73]:
# Descomprimimos el zip en la carpeta res/
# descomprimiendo archivo zip
ruta_ext = os.path.join("res")
# with garantiza que el archivo zip se cierre al terminar
with zipfile.ZipFile(ruta, 'r') as z:
    # Mensaje informativo antes de extraer
    print('Extracting all files...')
    # extractall descomprime todos los archivos al directorio ruta_ext
    z.extractall(ruta_ext) # destino
    # Confirmación de que la extracción terminó
    print('Done!')
# take a look at readme y revisar formatos

Extracting all files...
Done!

In [74]:
# Ruta al archivo de usuarios dentro del dataset descomprimido
ruta_users = os.path.join("res", "ml-1m", "users.dat")

In [75]:
# Lectura inicial sin nombres de columnas (Pandas infiere cabecera)
# Leemos datos desde archivo
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0, engine='python')
# Vista previa: columnas sin nombre y separador '::'
display(users_dataset)

      F  1.1  10  48067
1
2     M   56  16  70072
3     M   25  15  55117
4     M   45   7  02460
5     M   25  20  55455
6     F   50   9  55117
...  ..  ...  ..    ...
6036  F   25  15  32603
6037  F   45   1  76006
6038  F   56   1  14706
6039  F   45   0  01060
6040  M   25   6  11106

[6039 rows x 4 columns]

In [76]:
# Varios problemas
# sin cabecera! primer valor se ha perdido
# las columnas no tienen nombres
pd.read_csv?

In [77]:
# Lectura correcta: sin cabecera, con nombres y separador '::'
# especificar nombres, cargar sin cabecera
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
                           # header=None: el archivo no tiene fila de cabecera
                           header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],
                           # engine='python' necesario para separadores de más de 1 carácter
                           engine='python')
# DataFrame con columnas nombradas correctamente
display(users_dataset)

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460
5           M   25          20    55455
...       ...  ...         ...      ...
6036        F   25          15    32603
6037        F   45           1    76006
6038        F   56           1    14706
6039        F   45           0    01060
6040        M   25           6    11106

[6040 rows x 4 columns]

In [78]:
# samplear la tabla
display(users_dataset.sample(10))

       Gender  Age  Occupation Zip-code
UserID
2228        M   25          12    60025
3664        F   35           1    94043
3171        F   50           3    10128
38          F   18           4    02215
1974        M   35          17    12159
1318        M   18          16    94014
2221        M   56          17    94931
3215        F   50          13    55447
97          F   35           3    66210
346         F   25           0    55110

In [79]:
# samplear la cabeza
display(users_dataset.head(4))

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
2           M   56          16    70072
3           M   25          15    55117
4           M   45           7    02460

In [80]:
# samplear la cola
display(users_dataset.tail(10))

       Gender  Age  Occupation Zip-code
UserID
6031        F   18           0    45123
6032        M   45           7    55108
6033        M   50          13    78232
6034        M   25          14    94117
6035        F   25           1    78734
6036        F   25          15    32603
6037        F   45           1    76006
6038        F   56           1    14706
6039        F   45           0    01060
6040        M   25           6    11106

In [81]:
# tipos de datos sobre las columnas
users_dataset.dtypes

Gender          str
Age           int64
Occupation    int64
Zip-code        str
dtype: object

In [82]:
# Filtrado con str.len(): códigos postales con más de 5 caracteres
# str.len() mide longitud del string; >5 detecta formatos anómalos del zip
display(users_dataset[users_dataset['Zip-code'].str.len() > 5])

       Gender  Age  Occupation    Zip-code
UserID
161         M   45          16  98107-2117
233         F   45          20  37919-4204
293         M   56           1  55337-4056
458         M   50          16  55405-2546
506         M   25          16  55103-1006
...       ...  ...         ...         ...
5682        M   18           0  23455-4959
5904        F   45          12      954025
5925        F   25           0  90035-4444
5967        M   50          16  73069-5429
5985        F   18           4  78705-5221

[81 rows x 4 columns]

In [83]:
# información general sobre atributos numéricos
display(users_dataset.describe())

               Age   Occupation
count  6040.000000  6040.000000
mean     30.639238     8.146854
std      12.895962     6.329511
min       1.000000     0.000000
25%      25.000000     3.000000
50%      25.000000     7.000000
75%      35.000000    14.000000
max      56.000000    20.000000

In [84]:
# info() resume columnas, tipos, memoria y conteo de no-nulos
users_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 6040 entries, 1 to 6040
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Gender      6040 non-null   str
 1   Age         6040 non-null   int64
 2   Occupation  6040 non-null   int64
 3   Zip-code    6040 non-null   str
dtypes: int64(2), str(2)
memory usage: 188.9 KB

In [85]:
# incluir otros atributos (no todo tiene sentido)
display(users_dataset.describe(include='all'))

       Gender          Age   Occupation Zip-code
count    6040  6040.000000  6040.000000     6040
unique      2          NaN          NaN     3439
top         M          NaN          NaN    48104
freq     4331          NaN          NaN       19
mean      NaN    30.639238     8.146854      NaN
std       NaN    12.895962     6.329511      NaN
min       NaN     1.000000     0.000000      NaN
25%       NaN    25.000000     3.000000      NaN
50%       NaN    25.000000     7.000000      NaN
75%       NaN    35.000000    14.000000      NaN
max       NaN    56.000000    20.000000      NaN

In [86]:
# cuántos usuarios son mujeres (Gender='F')
len(users_dataset[users_dataset['Gender'] == 'F'])
#select count(*) from users_dataset where users_dataset.Gender = 'F'

1709

In [87]:
# Age==1 en MovieLens codifica menores de edad (código de edad 1)
# mostrar solo los menores de edad
under_age = users_dataset[users_dataset['Age'] == 1]
# Contamos cuántos usuarios tienen ese código de edad
print(len(under_age))
# Muestra 10 filas aleatorias del subconjunto filtrado
display(under_age.sample(10))

222

       Gender  Age  Occupation Zip-code
UserID
1926        F    1           0    95404
5953        M    1          10    21030
1568        F    1          10    94086
349         M    1          10    08035
3190        M    1          17    97062
875         M    1          10    94707
1195        F    1          10    13907
5973        M    1          10    54701
2108        M    1          10    60462
1458        M    1           0    08055

In [88]:
# SettingWithCopyWarning: modificar un slice puede no persistir o ser ambiguo
# filtrar edad incorrecta (mínimo 18) SettingWithCopyWarning!!!
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
                           # Sin cabecera: asignamos nombres manualmente
                           header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],
                           # Motor Python para parsear separador '::'
                           engine='python')
# Filtramos usuarios con código de edad 1 (menores)
under_age = users_dataset[users_dataset['Age'] == 1]
# loc['Age'] intenta modificar la columna en el slice → warning
under_age.loc['Age'] = np.nan
# El cambio puede no reflejarse en users_dataset original
display(under_age.head())
# users_dataset[users_dataset['Age'] < 18] = under_age
# display(users_dataset)

       Gender  Age  Occupation Zip-code
UserID
1           F  1.0        10.0    48067
19          M  1.0        10.0    48073
51          F  1.0        10.0    10562
75          F  1.0        10.0    01748
86          F  1.0        10.0    54467

In [89]:
# Solución correcta: copiar el slice antes de modificar y reasignar
# filtrar edad incorrecta (mínimo 18) Fixing it by Copying the slice
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
                           # Recargamos con nombres de columnas explícitos
                           header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],
                           # engine='python' para el separador '::'
                           engine='python')
# Subconjunto de menores de edad (vista del original)
under_age = users_dataset[users_dataset['Age'] == 1]
# .copy() crea copia independiente para modificar sin warning
under_age_copy = under_age.copy()
# Estado antes de anular la edad
display(under_age_copy.head())
# Anulamos Age con NaN en la copia (seguro, no afecta users_dataset aún)
under_age_copy['Age'] = np.nan
# Copia modificada con Age=NaN
display(under_age_copy.head())
# Reasignamos las filas filtradas en el DataFrame original
users_dataset[users_dataset['Age'] == 1] = under_age_copy # sets the rows according to the indexes
# users_dataset ahora refleja los cambios en las filas de menores
display(users_dataset.head())

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
19          M    1          10    48073
51          F    1          10    10562
75          F    1          10    01748
86          F    1          10    54467

       Gender  Age  Occupation Zip-code
UserID
1           F  NaN          10    48067
19          M  NaN          10    48073
51          F  NaN          10    10562
75          F  NaN          10    01748
86          F  NaN          10    54467

       Gender   Age  Occupation Zip-code
UserID
1           F   NaN          10    48067
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455

In [90]:
# Alternativa: modificar con loc en el DataFrame y eliminar NaN
# filtrar edad incorrecta (mínimo 18) Remove them from the dataset
users_dataset = pd.read_csv(ruta_users, sep='::', index_col=0,
                           # Carga con nombres de columnas y sin cabecera
                           header=None, names=['UserID','Gender','Age','Occupation','Zip-code'],
                           # Separador '::' requiere engine='python'
                           engine='python')
# Vista de 4 menores de edad antes de limpiar
display(users_dataset[users_dataset['Age'] == 1].head(4))
# loc con máscara: asigna NaN solo en filas donde Age==1
users_dataset.loc[users_dataset['Age'] == 1, 'Age'] = np.nan
# DataFrame con edades anuladas en menores
display(users_dataset)
# Filas donde Age quedó como NaN tras la asignación
display(users_dataset.loc[pd.isnull(users_dataset['Age'])].head(4))
# Detectamos valores nulos (NaN)
# drop elimina filas cuyo índice está en el conjunto de Age nulo
users_dataset.drop(users_dataset[pd.isnull(users_dataset['Age'])].index, inplace = True)
# DataFrame sin usuarios con edad inválida
display(users_dataset.head(4))

       Gender  Age  Occupation Zip-code
UserID
1           F    1          10    48067
19          M    1          10    48073
51          F    1          10    10562
75          F    1          10    01748

       Gender   Age  Occupation Zip-code
UserID
1           F   NaN          10    48067
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455
...       ...   ...         ...      ...
6036        F  25.0          15    32603
6037        F  45.0           1    76006
6038        F  56.0           1    14706
6039        F  45.0           0    01060
6040        M  25.0           6    11106

[6040 rows x 4 columns]

       Gender  Age  Occupation Zip-code
UserID
1           F  NaN          10    48067
19          M  NaN          10    48073
51          F  NaN          10    10562
75          F  NaN          10    01748

       Gender   Age  Occupation Zip-code
UserID
2           M  56.0          16    70072
3           M  25.0          15    55117
4           M  45.0           7    02460
5           M  25.0          20    55455

In [91]:
# Agrupar datos por atributos
display(users_dataset.groupby(by='Gender').describe())

           Age                                                     Occupation  \
         count       mean        std   min   25%   50%   75%   max      count
Gender
F       1631.0  32.287554  11.792015  18.0  25.0  25.0  45.0  56.0     1631.0
M       4187.0  31.568665  11.716053  18.0  25.0  25.0  35.0  56.0     4187.0


            mean       std  min  25%  50%   75%   max
Gender
F       6.498467  5.960285  0.0  1.0  4.0  11.0  20.0
M       8.743253  6.441753  0.0  4.0  7.0  15.0  20.0

In [92]:
# Grabar la tabla modificada
# Cambiar el separador a ','
# Guardar NaN como 'null'
ruta_output = os.path.join('res', 'ml-1m', 'o_users_processed.csv')
# Escribimos datos en archivo
users_dataset.to_csv(ruta_output, sep=',',na_rep='null')

# 7 Ejercicios

• Hacer un análisis general de los otros dos archivos CSV en ml-1m ('movies.dat' y 'ratings.dat')
• Analizando el dataset ratings.dat, ¿hay algún usuario que no tenga ninguna review? ¿Cuántos tienen menos de 30 reviews?

In [93]:
# Cargamos el archivo de valoraciones (ratings) del dataset MovieLens
# especificar nombres, cargar sin cabecera
import os
# Importamos Pandas: DataFrames y Series
import pandas as pd
# Ruta al archivo ratings.dat dentro de ml-1m/
ruta_ratings = os.path.join("res", "ml-1m", "ratings.dat")
# Leemos datos desde archivo
ratings_dataset = pd.read_csv(ruta_ratings, sep='::',
                              # Sin cabecera en el archivo original
                              header=None, names=['UserID','MovieID','Rating','Timestamp'],
                              # engine='python' para separador de doble dos puntos
                              engine='python')
# Tabla de valoraciones: usuario, película, nota y timestamp
display(ratings_dataset)

         UserID  MovieID  Rating  Timestamp
0             1     1193       5  978300760
1             1      661       3  978302109
2             1      914       3  978301968
3             1     3408       4  978300275
4             1     2355       5  978824291
...         ...      ...     ...        ...
1000204    6040     1091       1  956716541
1000205    6040     1094       5  956704887
1000206    6040      562       5  956704746
1000207    6040     1096       4  956715648
1000208    6040     1097       4  956715569

[1000209 rows x 4 columns]

In [94]:
# Comparamos usuarios totales vs usuarios que tienen al menos una review
# hay algún usuario que no tenga ninguna review
# groupby('UserID') agrupa por usuario; len cuenta grupos con al menos 1 rating
n_users_with_reviews = len(ratings_dataset.groupby(by='UserID'))
# Usuarios que han valorado al menos una película
print(n_users_with_reviews)
# Total de usuarios registrados en users.dat
n_users = len(users_dataset)
# Usuarios en el registro
print(n_users)
# Diferencia: usuarios sin ninguna valoración
print(n_users - n_users_with_reviews)

6040
5818
-222

In [95]:
# filter + lambda: usuarios con menos de 30 valoraciones
# Cuántos tienen menos de 30 reviews
# groupby agrupa por UserID; filter conserva grupos donde len(x)<30
ratings_under_30 = ratings_dataset.groupby(['UserID'])['UserID'].filter(lambda x: len(x) < 30).value_counts()
# Conteo de cuántas veces aparece cada UserID en el filtro
display(ratings_under_30)
# Número de usuarios con menos de 30 reviews
print(len(ratings_under_30))

UserID
71      29
221     29
234     29
246     29
282     29
        ..
5533    20
5725    20
5828    20
5904    20
6038    20
Name: count, Length: 751, dtype: int64

751